window.QP_CONFIG = {
  "baseUrl": "https://your-domain.com/quality-pictionary",
  "sets": {
    "A": [
      "assets/sets/A/01.png",
      "assets/sets/A/02.png",
      "assets/sets/A/03.png",
      "assets/sets/A/04.png",
      "assets/sets/A/05.png",
      "assets/sets/A/06.png",
      "assets/sets/A/07.png",
      "assets/sets/A/08.png",
      "assets/sets/A/09.png",
      "assets/sets/A/10.png",
      "assets/sets/A/11.png",
      "assets/sets/A/12.png",
      "assets/sets/A/13.png",
      "assets/sets/A/14.png",
      "assets/sets/A/15.png",
      "assets/sets/A/16.png",
      "assets/sets/A/17.png",
      "assets/sets/A/18.png",
      "assets/sets/A/19.png",
      "assets/sets/A/20.png"
    ],
    "B": [
      "assets/sets/B/01.png",
      "assets/sets/B/02.png",
      "assets/sets/B/03.png",
      "assets/sets/B/04.png",
      "assets/sets/B/05.png",
      "assets/sets/B/06.png",
      "assets/sets/B/07.png",
      "assets/sets/B/08.png",
      "assets/sets/B/09.png",
      "assets/sets/B/10.png",
      "assets/sets/B/11.png",
      "assets/sets/B/12.png",
      "assets/sets/B/13.png",
      "assets/sets/B/14.png",
      "assets/sets/B/15.png",
      "assets/sets/B/16.png",
      "assets/sets/B/17.png",
      "assets/sets/B/18.png",
      "assets/sets/B/19.png",
      "assets/sets/B/20.png"
    ],
    "C": [
      "assets/sets/C/01.png",
      "assets/sets/C/02.png",
      "assets/sets/C/03.png",
      "assets/sets/C/04.png",
      "assets/sets/C/05.png",
      "assets/sets/C/06.png",
      "assets/sets/C/07.png",
      "assets/sets/C/08.png",
      "assets/sets/C/09.png",
      "assets/sets/C/10.png",
      "assets/sets/C/11.png",
      "assets/sets/C/12.png",
      "assets/sets/C/13.png",
      "assets/sets/C/14.png",
      "assets/sets/C/15.png",
      "assets/sets/C/16.png",
      "assets/sets/C/17.png",
      "assets/sets/C/18.png",
      "assets/sets/C/19.png",
      "assets/sets/C/20.png"
    ]
  },
  "answers": {
    "A": [
      "Answer A01",
      "Answer A02",
      "Answer A03",
      "Answer A04",
      "Answer A05",
      "Answer A06",
      "Answer A07",
      "Answer A08",
      "Answer A09",
      "Answer A10",
      "Answer A11",
      "Answer A12",
      "Answer A13",
      "Answer A14",
      "Answer A15",
      "Answer A16",
      "Answer A17",
      "Answer A18",
      "Answer A19",
      "Answer A20"
    ],
    "B": [
      "Answer B01",
      "Answer B02",
      "Answer B03",
      "Answer B04",
      "Answer B05",
      "Answer B06",
      "Answer B07",
      "Answer B08",
      "Answer B09",
      "Answer B10",
      "Answer B11",
      "Answer B12",
      "Answer B13",
      "Answer B14",
      "Answer B15",
      "Answer B16",
      "Answer B17",
      "Answer B18",
      "Answer B19",
      "Answer B20"
    ],
    "C": [
      "Answer C01",
      "Answer C02",
      "Answer C03",
      "Answer C04",
      "Answer C05",
      "Answer C06",
      "Answer C07",
      "Answer C08",
      "Answer C09",
      "Answer C10",
      "Answer C11",
      "Answer C12",
      "Answer C13",
      "Answer C14",
      "Answer C15",
      "Answer C16",
      "Answer C17",
      "Answer C18",
      "Answer C19",
      "Answer C20"
    ]
  },
  "perClueSeconds": 45,
  "requirePasscode": true,
  "passcode": "QUALITY"
};